//! Fusion-Design 代码导出 — 消费 `fd-canvas-core::PenDocument`，
//! 生成 HTML / React / Tailwind 代码。
//!
//! 对应 PRD 模块 4「Fusion Code 双向打通」的正向导出能力。
//! 设计参照 OpenPencil `op-codegen` 的 `Codegen` trait 形状，
//! 但消费自研的 `PenDocument`（非 jian-ops-schema），零外部依赖。

use fd_canvas_core::{NodeKind, Page, PenDocument, PenNode};
use fd_design_system::DesignSystemRegistry;

/// 代码生成目标框架。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenTarget {
    /// 纯 HTML + 内联 CSS（静态预览）。
    Html,
    /// React 函数组件 + Tailwind class。
    ReactTailwind,
    /// 仅 Tailwind class 字符串（供嵌入）。
    TailwindOnly,
}

impl CodegenTarget {
    pub fn label(self) -> &'static str {
        match self {
            Self::Html => "html",
            Self::ReactTailwind => "react-tailwind",
            Self::TailwindOnly => "tailwind-only",
        }
    }
}

/// 代码生成器 trait。
pub trait Codegen {
    fn target(&self) -> CodegenTarget;
    fn generate(&self, doc: &PenDocument) -> String;
}

/// HTML 静态生成器。
pub struct HtmlCodegen;

impl Codegen for HtmlCodegen {
    fn target(&self) -> CodegenTarget { CodegenTarget::Html }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::from("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n");
        // 注入设计 Token CSS 变量（若文档声明了 design system）
        if let Some(ds_id) = &doc.active_design_system {
            out.push_str(&format!("<!-- design-system: {ds_id} -->\n"));
        }
        out.push_str("</head>\n<body>\n");
        for page in &doc.pages {
            out.push_str(&render_page_html(page));
        }
        out.push_str("</body>\n</html>\n");
        out
    }
}

/// React + Tailwind 生成器。
pub struct ReactTailwindCodegen {
    pub component_name: String,
}

impl Codegen for ReactTailwindCodegen {
    fn target(&self) -> CodegenTarget { CodegenTarget::ReactTailwind }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::new();
        out.push_str(&format!("// Generated by fusion-design — {}\n", self.target().label()));
        out.push_str(&format!("export function {}() {{\n  return (\n", self.component_name));
        out.push_str("    <div className=\"flex flex-col\">\n");
        for page in &doc.pages {
            out.push_str(&render_page_react(page));
        }
        out.push_str("    </div>\n  );\n}\n");
        out
    }
}

/// Tailwind-only 生成器（仅 class 字符串）。
pub struct TailwindOnlyCodegen;

impl Codegen for TailwindOnlyCodegen {
    fn target(&self) -> CodegenTarget { CodegenTarget::TailwindOnly }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::new();
        for page in &doc.pages {
            for node in &page.nodes {
                out.push_str(&node_to_tailwind(node));
                out.push('\n');
            }
        }
        out
    }
}

// ── 渲染辅助 ──

fn render_page_html(page: &Page) -> String {
    let mut out = format!("<section data-page=\"{}\" style=\"width:{}px;height:{}px;position:relative;\">\n",
        page.id, page.width as i32, page.height as i32);
    for node in &page.nodes {
        out.push_str(&node_to_html(node));
    }
    out.push_str("</section>\n");
    out
}

fn render_page_react(page: &Page) -> String {
    let mut out = format!("      {{/* page: {} */}}\n", page.id);
    for node in &page.nodes {
        out.push_str(&node_to_react(node));
    }
    out
}

fn node_to_html(node: &PenNode) -> String {
    let style = format_style_inline(node);
    match node.kind {
        NodeKind::Rect | NodeKind::Circle => {
            let tag = match node.kind { NodeKind::Circle => "div", _ => "div" };
            let extra = if matches!(node.kind, NodeKind::Circle) {
                "border-radius:50%;"
            } else {
                ""
            };
            format!("<{tag} data-id=\"{}\" style=\"{}{}\"></{tag}>\n", node.id, style, extra)
        }
        NodeKind::Text => format!("<div data-id=\"{}\" style=\"{}\">{}</div>\n",
            node.id, style, node.text.as_deref().unwrap_or("")),
        NodeKind::Image => format!("<img data-id=\"{}\" style=\"{}\" alt=\"\"/>\n", node.id, style),
        NodeKind::Group => {
            let mut s = format!("<div data-id=\"{}\" style=\"{}\">\n", node.id, style);
            for c in &node.children {
                s.push_str(&node_to_html(c));
            }
            s.push_str("</div>\n");
            s
        }
    }
}

fn node_to_react(node: &PenNode) -> String {
    let cls = node_to_tailwind(node);
    match node.kind {
        NodeKind::Rect | NodeKind::Circle => {
            let extra = if matches!(node.kind, NodeKind::Circle) { " rounded-full" } else { "" };
            format!("      <div className=\"{}{}\" data-id=\"{}\"/>\n", cls, extra, node.id)
        }
        NodeKind::Text => format!("      <div className=\"{}\" data-id=\"{}\">{}</div>\n",
            cls, node.id, node.text.as_deref().unwrap_or("")),
        NodeKind::Image => format!("      <img className=\"{}\" data-id=\"{}\" alt=\"\"/>\n", cls, node.id),
        NodeKind::Group => {
            let mut s = format!("      <div className=\"{}\" data-id=\"{}\">\n", cls, node.id);
            for c in &node.children {
                s.push_str(&node_to_react(c));
            }
            s.push_str("      </div>\n");
            s
        }
    }
}

fn node_to_tailwind(node: &PenNode) -> String {
    // MVP：绝对定位 + 尺寸 class。颜色用 arbitrary value `bg-[#xxx]`。
    let mut cls = vec![
        "absolute".to_string(),
        format!("left-[{}px]", node.x as i32),
        format!("top-[{}px]", node.y as i32),
    ];
    if node.w > 0.0 {
        cls.push(format!("w-[{}px]", node.w as i32));
    }
    if node.h > 0.0 {
        cls.push(format!("h-[{}px]", node.h as i32));
    }
    if let Some(fill) = &node.style.fill {
        cls.push(format!("bg-[{}]", fill));
    }
    if let Some(stroke) = &node.style.stroke {
        cls.push(format!("border-2 border-[{}]", stroke));
    }
    if let Some(r) = node.style.radius {
        cls.push(format!("rounded-[{}px]", r as i32));
    }
    if let Some(op) = node.style.opacity {
        cls.push(format!("opacity-[{}]", op));
    }
    cls.join(" ")
}

fn format_style_inline(node: &PenNode) -> String {
    let mut parts = vec![
        format!("position:absolute;left:{}px;top:{}px;", node.x as i32, node.y as i32),
    ];
    if node.w > 0.0 {
        parts.push(format!("width:{}px;", node.w as i32));
    }
    if node.h > 0.0 {
        parts.push(format!("height:{}px;", node.h as i32));
    }
    if let Some(fill) = &node.style.fill {
        parts.push(format!("background:{};", fill));
    }
    if let Some(stroke) = &node.style.stroke {
        parts.push(format!("border:2px solid {};", stroke));
    }
    if let Some(r) = node.style.radius {
        parts.push(format!("border-radius:{}px;", r as i32));
    }
    if let Some(op) = node.style.opacity {
        parts.push(format!("opacity:{};", op));
    }
    parts.join("")
}

/// 按 design system 解析 token 引用（如 `color.bg` → 实际 hex）。
///
/// MVP 简化：节点 style 中若出现 `token:color.bg` 形式，查 registry 替换。
pub fn resolve_tokens(doc: &PenDocument, reg: &DesignSystemRegistry) -> PenDocument {
    let mut resolved = doc.clone();
    let resolve = |v: &Option<String>| -> Option<String> {
        let s = v.as_deref()?;
        if let Some(rest) = s.strip_prefix("token:") {
            return reg.lookup(rest).and_then(|tv| match tv {
                fd_design_system::TokenValue::Color(c) => Some(c.clone()),
                fd_design_system::TokenValue::String(s) => Some(s.clone()),
                _ => None,
            });
        }
        Some(s.to_string())
    };
    for page in &mut resolved.pages {
        for node in &mut page.nodes {
            node.style.fill = resolve(&node.style.fill);
            node.style.stroke = resolve(&node.style.stroke);
        }
    }
    resolved
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_doc() -> PenDocument {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p1", "Home", 100.0, 100.0);
        let mut rect = PenNode::rect("n1", 10.0, 20.0, 50.0, 30.0);
        rect.style.fill = Some("#FFF".into());
        rect.style.stroke = Some("#000".into());
        page.add(rect);
        page.add(PenNode::text("n2", 5.0, 5.0, "hello"));
        doc.add_page(page);
        doc
    }

    #[test]
    fn html_codegen_basic() {
        let out = HtmlCodegen.generate(&sample_doc());
        assert!(out.contains("<!DOCTYPE html>"));
        assert!(out.contains("data-id=\"n1\""));
        assert!(out.contains("background:#FFF"));
        assert!(out.contains("hello"));
    }

    #[test]
    fn react_tailwind_basic() {
        let gen = ReactTailwindCodegen { component_name: "Home".into() };
        let out = gen.generate(&sample_doc());
        assert!(out.contains("export function Home()"));
        assert!(out.contains("left-[10px]"));
        assert!(out.contains("bg-[#FFF]"));
    }

    #[test]
    fn tailwind_only_basic() {
        let out = TailwindOnlyCodegen.generate(&sample_doc());
        assert!(out.contains("absolute"));
        assert!(out.contains("left-[10px]"));
    }

    #[test]
    fn html_circle_gets_radius() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut c = PenNode::rect("c", 0.0, 0.0, 10.0, 10.0);
        c.kind = NodeKind::Circle;
        page.add(c);
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("border-radius:50%"));
    }

    #[test]
    fn react_group_recurses_children() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let g = PenNode::group("g", 0.0, 0.0, vec![PenNode::rect("inner", 1.0, 1.0, 5.0, 5.0)]);
        page.add(g);
        doc.add_page(page);
        let gen = ReactTailwindCodegen { component_name: "C".into() };
        let out = gen.generate(&doc);
        assert!(out.contains("data-id=\"inner\""));
    }

    #[test]
    fn html_group_recurses_children() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let g = PenNode::group("g", 0.0, 0.0, vec![PenNode::rect("inner", 0.0, 0.0, 5.0, 5.0)]);
        page.add(g);
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("data-id=\"inner\""));
    }

    #[test]
    fn codegen_target_labels() {
        assert_eq!(CodegenTarget::Html.label(), "html");
        assert_eq!(CodegenTarget::ReactTailwind.label(), "react-tailwind");
    }

    #[test]
    fn resolve_tokens_replaces_token_refs() {
        use fd_design_system::DesignSystemRegistry;
        let mut reg = DesignSystemRegistry::new();
        reg.register_builtin();
        reg.activate("apple-hig").unwrap();
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n", 0.0, 0.0, 10.0, 10.0);
        n.style.fill = Some("token:color.accent".into());
        page.add(n);
        doc.add_page(page);
        let resolved = resolve_tokens(&doc, &reg);
        assert_eq!(resolved.pages[0].nodes[0].style.fill.as_deref(), Some("#007AFF"));
    }

    #[test]
    fn resolve_tokens_passthrough_non_token() {
        use fd_design_system::DesignSystemRegistry;
        let reg = DesignSystemRegistry::new();
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n", 0.0, 0.0, 10.0, 10.0);
        n.style.fill = Some("#ABC".into());
        page.add(n);
        doc.add_page(page);
        let resolved = resolve_tokens(&doc, &reg);
        assert_eq!(resolved.pages[0].nodes[0].style.fill.as_deref(), Some("#ABC"));
    }
}
