// Callers: DesignBridge.swift, fd-cli codegen subcommand
// Affected API: CodegenTarget::SwiftUi added, SwiftUiCodegen struct, node_to_swiftui/render_page_swiftui helpers
// Data schemas: PenDocument→SwiftUI View code, Flex→HStack/VStack, Grid→SwiftUI Grid, Token→Color/Font extension
// User instruction: "按照P1~P6顺序实施所有未完成的任务" — Task #33 P5-4 SwiftUI 导出 target

//! Fusion-Design 代码导出 — 消费 `fd-canvas-core::PenDocument`，
//! 生成 HTML / React / Tailwind / SwiftUI 代码。
//!
//! 对应 PRD 模块 4「Fusion Code 双向打通」的正向导出能力。
//! 设计参照 OpenPencil `op-codegen` 的 `Codegen` trait 形状，
//! 但消费自研的 `PenDocument`（非 jian-ops-schema），零外部依赖。

use fd_canvas_core::{
    parse_hex_color, sanitize_css_value, FlexDirection, LayoutMode, NodeKind, Page, PenDocument,
    PenNode,
};
use fd_design_system::DesignSystemRegistry;
use std::collections::HashMap;

/// 代码生成目标框架。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenTarget {
    /// 纯 HTML + 内联 CSS（静态预览）。
    Html,
    /// React 函数组件 + Tailwind class。
    ReactTailwind,
    /// 仅 Tailwind class 字符串（供嵌入）。
    TailwindOnly,
    /// SwiftUI View 代码。
    SwiftUi,
}

impl CodegenTarget {
    pub fn label(self) -> &'static str {
        match self {
            Self::Html => "html",
            Self::ReactTailwind => "react-tailwind",
            Self::TailwindOnly => "tailwind-only",
            Self::SwiftUi => "swiftui",
        }
    }
}

/// 代码生成器 trait。
pub trait Codegen {
    fn target(&self) -> CodegenTarget;
    fn generate(&self, doc: &PenDocument) -> String;
}

/// HTML 静态生成器。
pub struct HtmlCodegen;

impl Codegen for HtmlCodegen {
    fn target(&self) -> CodegenTarget {
        CodegenTarget::Html
    }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::from("<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n");
        if let Some(ds_id) = &doc.active_design_system {
            out.push_str(&format!("<!-- design-system: {ds_id} -->\n"));
        }
        out.push_str("</head>\n<body>\n");
        for page in &doc.pages {
            out.push_str(&render_page_html(page));
        }
        out.push_str("</body>\n</html>\n");
        out
    }
}

/// React + Tailwind 生成器。
pub struct ReactTailwindCodegen {
    pub component_name: String,
}

impl Codegen for ReactTailwindCodegen {
    fn target(&self) -> CodegenTarget {
        CodegenTarget::ReactTailwind
    }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "// Generated by fusion-design — {}\n",
            self.target().label()
        ));
        out.push_str(&format!(
            "export function {}() {{\n  return (\n",
            self.component_name
        ));
        out.push_str("    <div className=\"flex flex-col\">\n");
        for page in &doc.pages {
            out.push_str(&render_page_react(page));
        }
        out.push_str("    </div>\n  );\n}\n");
        out
    }
}

/// Tailwind-only 生成器（仅 class 字符串）。
pub struct TailwindOnlyCodegen;

impl Codegen for TailwindOnlyCodegen {
    fn target(&self) -> CodegenTarget {
        CodegenTarget::TailwindOnly
    }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::new();
        for page in &doc.pages {
            for node in &page.nodes {
                out.push_str(&node_to_tailwind(node));
                out.push('\n');
            }
        }
        out
    }
}

/// SwiftUI View 生成器。
pub struct SwiftUiCodegen {
    pub view_name: String,
}

impl Codegen for SwiftUiCodegen {
    fn target(&self) -> CodegenTarget {
        CodegenTarget::SwiftUi
    }
    fn generate(&self, doc: &PenDocument) -> String {
        let mut out = String::new();
        out.push_str("// Generated by fusion-design — swiftui\n");
        out.push_str("import SwiftUI\n\n");

        let token_exts = collect_token_extensions(doc);
        if !token_exts.is_empty() {
            out.push_str(&render_token_extensions(&token_exts));
            out.push('\n');
        }

        out.push_str(&format!("struct {}: View {{\n", self.view_name));
        out.push_str("    var body: some View {\n");
        out.push_str("        ScrollView {\n");
        for page in &doc.pages {
            out.push_str(&render_page_swiftui(page, 3));
        }
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n");
        out
    }
}

// ── SwiftUI 渲染辅助 ──

fn render_page_swiftui(page: &Page, indent: usize) -> String {
    let pad = "    ".repeat(indent);
    let mut out = format!("{}VStack(spacing: 0) {{\n", pad);
    for node in &page.nodes {
        out.push_str(&node_to_swiftui(node, indent + 1));
    }
    out.push_str(&format!("{}}}\n", pad));
    out
}

fn node_to_swiftui(node: &PenNode, indent: usize) -> String {
    node_to_swiftui_inner(node, indent, 0)
}

// C3 纵深防御：codegen 递归深度守卫。A4 已在反序列化层卡 MAX_NODE_DEPTH，
// 此处独立上限防任何绕过路径（如未来新增加载入口）的栈溢出。
const MAX_CODEGEN_DEPTH: usize = 128;

fn node_to_swiftui_inner(node: &PenNode, indent: usize, depth: usize) -> String {
    if depth > MAX_CODEGEN_DEPTH {
        return format!(
            "{}/* codegen depth limit reached */\n",
            "    ".repeat(indent)
        );
    }
    let pad = "    ".repeat(indent);
    let mut mods = vec![];

    if node.x != 0.0 || node.y != 0.0 {
        mods.push(format!(
            ".offset(x: {}, y: {})",
            node.x as i32, node.y as i32
        ));
    }
    if let Some(fill) = &node.style.fill {
        // R-6：fill 入 swift_ui_color("...") 的 Swift 字面量，须转义防注入。
        mods.push(format!(
            ".background(swift_ui_color(\"{}\"))",
            escape_swift_string(fill)
        ));
    }
    if let Some(stroke) = &node.style.stroke {
        // E-8：stroke_width 而非硬编码 lineWidth:1（对齐 HTML/Tailwind 路径）。
        // R-6：stroke 同入 Swift 字面量，转义。
        let sw = node.style.stroke_width.unwrap_or(1.0);
        mods.push(format!(".overlay(RoundedRectangle(cornerRadius: {}).stroke(swift_ui_color(\"{}\"), lineWidth: {}))",
            node.style.radius.unwrap_or(0.0) as i32, escape_swift_string(stroke), sw as i32));
    }
    if let Some(r) = node.style.radius {
        if r > 0.0 {
            mods.push(format!(".cornerRadius({})", r as i32));
        }
    }
    if let Some(op) = node.style.opacity {
        if (op - 1.0).abs() > f64::EPSILON {
            mods.push(format!(".opacity({})", op));
        }
    }
    // E-8：SwiftUI 路径补 rotation/z_index/font_family（此前仅 font_size，
    // 对齐 HTML/Tailwind/React 路径 5 维完整渲染）。
    if node.rotation != 0.0 {
        mods.push(format!(
            ".rotationEffect(.degrees({}))",
            node.rotation as i32
        ));
    }
    if node.z_index != 0 {
        mods.push(format!(".zIndex({})", node.z_index));
    }
    if let Some(fs) = node.style.font_size {
        if let Some(ff) = &node.style.font_family {
            // R-6：font_family 入字面量，转义防注入
            mods.push(format!(
                ".font(.custom(\"{}\", size: {}))",
                escape_swift_string(ff),
                fs as i32
            ));
        } else {
            mods.push(format!(".font(.system(size: {}))", fs as i32));
        }
    } else if let Some(ff) = &node.style.font_family {
        mods.push(format!(
            ".font(.custom(\"{}\", size: 16))",
            escape_swift_string(ff)
        ));
    }

    let mod_str = if mods.is_empty() {
        String::new()
    } else {
        mods.join("")
    };

    let rendered = match node.kind {
        NodeKind::Rect => {
            let w = if node.w > 0.0 {
                format!("width: {}", node.w as i32)
            } else {
                String::new()
            };
            let h = if node.h > 0.0 {
                format!("height: {}", node.h as i32)
            } else {
                String::new()
            };
            let dims = match (w.is_empty(), h.is_empty()) {
                (true, true) => String::new(),
                (true, false) => format!(".frame({})", h),
                (false, true) => format!(".frame({})", w),
                (false, false) => format!(".frame({}, {})", w, h),
            };
            format!("{}Color.clear{}{}\n", pad, dims, mod_str)
        }
        NodeKind::Circle => {
            let size = if node.w > 0.0 {
                node.w as i32
            } else {
                node.h as i32
            };
            format!(
                "{}Circle(){}.frame(width: {}, height: {})\n",
                pad, mod_str, size, size
            )
        }
        NodeKind::Text => {
            let txt = node.text.as_deref().unwrap_or("");
            let escaped = txt.replace('\\', "\\\\").replace('"', "\\\"");
            format!("{}Text(\"{}\"){}\n", pad, escaped, mod_str)
        }
        NodeKind::Image => {
            format!("{}Image(systemName: \"photo\"){}\n", pad, mod_str)
        }
        NodeKind::Group => {
            let (container, spacing) = match &node.style.layout {
                LayoutMode::Flex(flex) => {
                    let sp = if flex.gap > 0.0 {
                        format!("spacing: {}", flex.gap as i32)
                    } else {
                        "spacing: 0".to_string()
                    };
                    match flex.direction {
                        FlexDirection::Row | FlexDirection::RowReverse => ("HStack", sp),
                        FlexDirection::Column | FlexDirection::ColumnReverse => ("VStack", sp),
                    }
                }
                LayoutMode::Grid(_) => ("LazyVGrid", "spacing: 8".to_string()),
                LayoutMode::Free => ("ZStack", String::new()),
            };
            let mut out = if spacing.is_empty() {
                format!("{}{} {{\n", pad, container)
            } else {
                format!("{}{}({}) {{\n", pad, container, spacing)
            };
            for c in &node.children {
                out.push_str(&node_to_swiftui_inner(c, indent + 1, depth + 1));
            }
            out.push_str(&format!("{}}}{}\n", pad, mod_str));
            out
        }
    };

    // 非 Group 叶子节点带子节点：用 ZStack 承载叶子 + 子节点，避免丢嵌套（#7）
    if !matches!(node.kind, NodeKind::Group) && !node.children.is_empty() {
        let mut out = format!("{}ZStack {{\n", pad);
        out.push_str(&rendered);
        for c in &node.children {
            out.push_str(&node_to_swiftui_inner(c, indent + 1, depth + 1));
        }
        out.push_str(&pad);
        out.push('}');
        out.push('\n');
        out
    } else {
        rendered
    }
}

fn swift_ui_color(color: &str) -> String {
    if let Some(rest) = color.strip_prefix("token:") {
        return format!("DesignTokens.{}", rest.replace('.', "_"));
    }
    // C-2/A-2：经共享 parse_hex_color（ASCII 门控，CJK/emoji 返 None 不 panic）。
    if let Some([r, g, b]) = parse_hex_color(color) {
        format!("Color(red: {}/255, green: {}/255, blue: {}/255)", r, g, b)
    } else {
        // R-6：非 hex/token 的颜色名（如 CSS 命名色）入 Color("...") 字符串字面量，
        // 须转义引号/反斜杠/换行，防 `red"); evil(); /*` 注入可执行 Swift。
        format!("Color(\"{}\")", escape_swift_string(color))
    }
}

/// R-6：Swift 字符串字面量转义。注入面：fill/stroke/font_family/color 经 format!
/// 塞入 `"...""` 字面量，未转义的 `"`/`\`/换行可闭合字面量注入可执行代码。
/// 转义顺序：先 `\`（避免二次转义后续插入的反斜杠），再 `"`，再换行符。
fn escape_swift_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

#[derive(Debug, Clone)]
struct TokenExt {
    swift_name: String,
    color_expr: String,
}

fn collect_token_extensions(doc: &PenDocument) -> Vec<TokenExt> {
    let mut seen = HashMap::new();
    for page in &doc.pages {
        collect_token_exts_from_nodes(&page.nodes, &mut seen);
    }
    let mut exts: Vec<TokenExt> = seen.into_values().collect();
    exts.sort_by(|a, b| a.swift_name.cmp(&b.swift_name));
    exts
}

fn collect_token_exts_from_nodes(nodes: &[PenNode], seen: &mut HashMap<String, TokenExt>) {
    for node in nodes {
        for (key, token_ref) in &node.style.design_token_refs {
            let swift_name = token_ref.replace('.', "_");
            if seen.contains_key(&swift_name) {
                continue;
            }
            let color_expr = match key.as_str() {
                "fill" => node.style.fill.as_deref().map(swift_ui_color),
                "stroke" => node.style.stroke.as_deref().map(swift_ui_color),
                _ => None,
            };
            if let Some(expr) = color_expr {
                seen.insert(
                    swift_name.clone(),
                    TokenExt {
                        swift_name,
                        color_expr: expr,
                    },
                );
            }
        }
        collect_token_exts_from_nodes(&node.children, seen);
    }
}

fn render_token_extensions(exts: &[TokenExt]) -> String {
    let mut out = String::from("extension Color {\n");
    out.push_str("    enum DesignTokens {\n");
    for ext in exts {
        out.push_str(&format!(
            "        static let {} = {}\n",
            ext.swift_name, ext.color_expr
        ));
    }
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out
}

// ── HTML/React 渲染辅助 ──

fn render_page_html(page: &Page) -> String {
    let mut out = format!(
        "<section data-page=\"{}\" style=\"width:{}px;height:{}px;position:relative;\">\n",
        page.id, page.width as i32, page.height as i32
    );
    for node in &page.nodes {
        out.push_str(&node_to_html(node));
    }
    out.push_str("</section>\n");
    out
}

fn render_page_react(page: &Page) -> String {
    let mut out = format!("      {{/* page: {} */}}\n", page.id);
    for node in &page.nodes {
        out.push_str(&node_to_react(node));
    }
    out
}

// HTML 实体转义（F1/XSS 修复）：node.text 来自 LLM 输出或 parse-html 解析的
// 不可信文本，原样拼进 HTML/JSX 会执行任意脚本。转义 5 个 HTML 特殊字符。
fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#x27;")
}

// E-10：CSS 颜色值净化。fill/stroke 来自 LLM 输出或 parse-html 不可信输入，
// 原样拼进 `background:{fill};` / Tailwind `bg-[{fill}]` 可逃逸属性注入任意 CSS
// （如 `red;} * {position:fixed;background:url(http://evil)` 破离线约束）。
// 拒绝 url()（离线硬约束 + 外网探测），剔除可逃逸属性边界的 `;{}`，保留 hex/命名色/rgb()。
fn sanitize_css_color(raw: &str) -> String {
    // C-6/A-3：共享 sanitize_css_value，比旧实现多剥 `"`（Tailwind 任意值 bg-[{v}] 逃逸点）。
    sanitize_css_value(raw, "transparent")
}

// E-10：node.id 经 escape_html 转义后安全用于属性值（转 " 防 `data-id="a" onclick=…` 注入）。
fn escape_attr(s: &str) -> String {
    escape_html(s)
}

fn node_to_html(node: &PenNode) -> String {
    node_to_html_inner(node, 0)
}

fn node_to_html_inner(node: &PenNode, depth: usize) -> String {
    if depth > MAX_CODEGEN_DEPTH {
        return "<!-- codegen depth limit reached -->\n".to_string();
    }
    let style = format_style_inline(node);
    // 子节点对任意 kind 均可能存在（parse-html 把带子节点的 <div> 映射为 Rect），
    // 统一收集后在各分支注入，避免叶子节点静默丢弃嵌套结构（#7）。
    let children: String = node
        .children
        .iter()
        .map(|c| node_to_html_inner(c, depth + 1))
        .collect();
    match node.kind {
        NodeKind::Rect | NodeKind::Circle => {
            let tag = "div";
            let extra = if matches!(node.kind, NodeKind::Circle) {
                "border-radius:50%;"
            } else {
                ""
            };
            if children.is_empty() {
                format!(
                    "<{tag} data-id=\"{}\" style=\"{}{}\"></{tag}>\n",
                    escape_attr(&node.id),
                    style,
                    extra
                )
            } else {
                format!(
                    "<{tag} data-id=\"{}\" style=\"{}{}\">{}</{tag}>\n",
                    escape_attr(&node.id),
                    style,
                    extra,
                    children
                )
            }
        }
        NodeKind::Text => format!(
            "<div data-id=\"{}\" style=\"{}\">{}{}</div>\n",
            escape_attr(&node.id),
            style,
            escape_html(node.text.as_deref().unwrap_or("")),
            children
        ),
        NodeKind::Image => {
            if children.is_empty() {
                format!(
                    "<img data-id=\"{}\" style=\"{}\" alt=\"\"/>\n",
                    escape_attr(&node.id),
                    style
                )
            } else {
                // <img> 为 void 元素；有子节点时外裹 div 承载嵌套结构
                format!(
                    "<div data-id=\"{}\" style=\"{}\"><img style=\"{}\" alt=\"\"/>{}</div>\n",
                    escape_attr(&node.id),
                    style,
                    style,
                    children
                )
            }
        }
        NodeKind::Group => {
            let mut s = format!(
                "<div data-id=\"{}\" style=\"{}\">\n",
                escape_attr(&node.id),
                style
            );
            s.push_str(&children);
            s.push_str("</div>\n");
            s
        }
    }
}

fn node_to_react(node: &PenNode) -> String {
    node_to_react_inner(node, 0)
}

fn node_to_react_inner(node: &PenNode, depth: usize) -> String {
    if depth > MAX_CODEGEN_DEPTH {
        return "{/* codegen depth limit reached */}\n".to_string();
    }
    let cls = node_to_tailwind(node);
    // 同 node_to_html：统一收集子节点并注入各分支，修复叶子节点丢嵌套（#7）。
    let children: String = node
        .children
        .iter()
        .map(|c| node_to_react_inner(c, depth + 1))
        .collect();
    match node.kind {
        NodeKind::Rect | NodeKind::Circle => {
            let extra = if matches!(node.kind, NodeKind::Circle) {
                " rounded-full"
            } else {
                ""
            };
            if children.is_empty() {
                format!(
                    "      <div className=\"{}{}\" data-id=\"{}\"/>\n",
                    cls,
                    extra,
                    escape_attr(&node.id)
                )
            } else {
                format!(
                    "      <div className=\"{}{}\" data-id=\"{}\">\n{}</div>\n",
                    cls,
                    extra,
                    escape_attr(&node.id),
                    children
                )
            }
        }
        NodeKind::Text => format!(
            "      <div className=\"{}\" data-id=\"{}\">{}{}</div>\n",
            cls,
            escape_attr(&node.id),
            escape_html(node.text.as_deref().unwrap_or("")),
            children
        ),
        NodeKind::Image => {
            if children.is_empty() {
                format!(
                    "      <img className=\"{}\" data-id=\"{}\" alt=\"\"/>\n",
                    cls,
                    escape_attr(&node.id)
                )
            } else {
                // <img> 自闭合；有子节点时外裹 div 承载
                format!(
                    "      <div className=\"{}\" data-id=\"{}\"><img alt=\"\"/>{}</div>\n",
                    cls,
                    escape_attr(&node.id),
                    children
                )
            }
        }
        NodeKind::Group => {
            let mut s = format!(
                "      <div className=\"{}\" data-id=\"{}\">\n",
                cls,
                escape_attr(&node.id)
            );
            s.push_str(&children);
            s.push_str("      </div>\n");
            s
        }
    }
}

fn node_to_tailwind(node: &PenNode) -> String {
    let mut cls: Vec<String> = Vec::new();
    // E-9：仅 Free 布局输出 absolute + left/top；Flex/Grid 走文档流。
    match &node.style.layout {
        LayoutMode::Free => {
            cls.push("absolute".into());
            cls.push(format!("left-[{}px]", node.x as i32));
            cls.push(format!("top-[{}px]", node.y as i32));
        }
        LayoutMode::Flex(p) => {
            cls.push("relative".into());
            cls.push("flex".into());
            cls.push(
                match p.direction {
                    FlexDirection::Row => "flex-row",
                    FlexDirection::RowReverse => "flex-row-reverse",
                    FlexDirection::Column => "flex-col",
                    FlexDirection::ColumnReverse => "flex-col-reverse",
                }
                .into(),
            );
            if p.gap > 0.0 {
                cls.push(format!("gap-[{}px]", p.gap as i32));
            }
            cls.push(
                match p.align_items {
                    fd_canvas_core::AlignItems::Start => "items-start",
                    fd_canvas_core::AlignItems::Center => "items-center",
                    fd_canvas_core::AlignItems::End => "items-end",
                    fd_canvas_core::AlignItems::Stretch => "items-stretch",
                }
                .into(),
            );
            cls.push(
                match p.justify_content {
                    fd_canvas_core::JustifyContent::Start => "justify-start",
                    fd_canvas_core::JustifyContent::Center => "justify-center",
                    fd_canvas_core::JustifyContent::End => "justify-end",
                    fd_canvas_core::JustifyContent::SpaceBetween => "justify-between",
                    fd_canvas_core::JustifyContent::SpaceAround => "justify-around",
                    fd_canvas_core::JustifyContent::SpaceEvenly => "justify-evenly",
                }
                .into(),
            );
            cls.push(
                match p.wrap {
                    fd_canvas_core::FlexWrap::NoWrap => "flex-nowrap",
                    fd_canvas_core::FlexWrap::Wrap => "flex-wrap",
                }
                .into(),
            );
        }
        LayoutMode::Grid(_) => {
            // Tailwind Grid 精细类需模板生成，此处用 arbitrary value 兜底；
            // 真实 grid 布局建议走 format_style_inline（grid-template-columns）。
            cls.push("relative".into());
            cls.push("grid".into());
        }
    }
    if node.w > 0.0 {
        cls.push(format!("w-[{}px]", node.w as i32));
    }
    if node.h > 0.0 {
        cls.push(format!("h-[{}px]", node.h as i32));
    }
    if let Some(fill) = &node.style.fill {
        cls.push(format!("bg-[{}]", sanitize_css_color(fill)));
    }
    if let Some(stroke) = &node.style.stroke {
        // E-8：输出 stroke_width 而非固定 border-2。
        let sw = node.style.stroke_width.unwrap_or(1.0);
        cls.push(format!("border-[{}px]", sw as i32));
        cls.push(format!("border-[{}]", sanitize_css_color(stroke)));
    }
    if let Some(r) = node.style.radius {
        cls.push(format!("rounded-[{}px]", r as i32));
    }
    if let Some(op) = node.style.opacity {
        cls.push(format!("opacity-[{}]", op));
    }
    // E-8：rotation / z_index / font。
    if node.rotation != 0.0 {
        cls.push(format!("rotate-[{}deg]", node.rotation));
    }
    if node.z_index != 0 {
        cls.push(format!("z-[{}]", node.z_index));
    }
    if let Some(fs) = node.style.font_size {
        cls.push(format!("text-[{}px]", fs as i32));
    }
    if let Some(ff) = &node.style.font_family {
        cls.push(format!("font-[{}]", sanitize_css_color(ff)));
    }
    cls.join(" ")
}

fn format_style_inline(node: &PenNode) -> String {
    let mut parts: Vec<String> = Vec::new();
    // E-9：仅 Free 布局输出 absolute + left/top；Flex/Grid 容器走文档流，
    // 由 display:flex/grid 驱动子元素排列，不强制 absolute。
    match &node.style.layout {
        LayoutMode::Free => {
            parts.push(format!(
                "position:absolute;left:{}px;top:{}px;",
                node.x as i32, node.y as i32
            ));
        }
        LayoutMode::Flex(p) => {
            parts.push("position:relative;".to_string());
            parts.extend(flex_css(p));
        }
        LayoutMode::Grid(g) => {
            parts.push("position:relative;".to_string());
            parts.extend(grid_css(g));
        }
    }
    if node.w > 0.0 {
        parts.push(format!("width:{}px;", node.w as i32));
    }
    if node.h > 0.0 {
        parts.push(format!("height:{}px;", node.h as i32));
    }
    if let Some(fill) = &node.style.fill {
        parts.push(format!("background:{};", sanitize_css_color(fill)));
    }
    if let Some(stroke) = &node.style.stroke {
        // E-8：输出 stroke_width 而非固定 2px。
        let sw = node.style.stroke_width.unwrap_or(1.0);
        parts.push(format!(
            "border:{}px solid {};",
            sw as i32,
            sanitize_css_color(stroke)
        ));
    }
    if let Some(r) = node.style.radius {
        parts.push(format!("border-radius:{}px;", r as i32));
    }
    if let Some(op) = node.style.opacity {
        parts.push(format!("opacity:{};", op));
    }
    // E-8：rotation / z_index。
    if node.rotation != 0.0 {
        parts.push(format!("transform:rotate({}deg);", node.rotation));
    }
    if node.z_index != 0 {
        parts.push(format!("z-index:{};", node.z_index));
    }
    // E-8：font_family / font_size（Text 节点字号字体，非 Text 节点亦输出供容器继承）。
    if let Some(fs) = node.style.font_size {
        parts.push(format!("font-size:{}px;", fs as i32));
    }
    if let Some(ff) = &node.style.font_family {
        parts.push(format!("font-family:{};", sanitize_css_color(ff)));
    }
    parts.join("")
}

/// E-9：FlexParams → CSS 声明片段（对齐 host-web 渲染约定）。
fn flex_css(p: &fd_canvas_core::FlexParams) -> Vec<String> {
    use fd_canvas_core::{AlignItems, FlexDirection, FlexWrap, JustifyContent};
    let mut v = vec!["display:flex;".to_string()];
    v.push(
        match p.direction {
            FlexDirection::Row => "flex-direction:row;",
            FlexDirection::RowReverse => "flex-direction:row-reverse;",
            FlexDirection::Column => "flex-direction:column;",
            FlexDirection::ColumnReverse => "flex-direction:column-reverse;",
        }
        .into(),
    );
    if p.gap > 0.0 {
        v.push(format!("gap:{}px;", p.gap as i32));
    }
    v.push(
        match p.align_items {
            AlignItems::Start => "align-items:flex-start;",
            AlignItems::Center => "align-items:center;",
            AlignItems::End => "align-items:flex-end;",
            AlignItems::Stretch => "align-items:stretch;",
        }
        .into(),
    );
    v.push(
        match p.justify_content {
            JustifyContent::Start => "justify-content:flex-start;",
            JustifyContent::Center => "justify-content:center;",
            JustifyContent::End => "justify-content:flex-end;",
            JustifyContent::SpaceBetween => "justify-content:space-between;",
            JustifyContent::SpaceAround => "justify-content:space-around;",
            JustifyContent::SpaceEvenly => "justify-content:space-evenly;",
        }
        .into(),
    );
    v.push(
        match p.wrap {
            FlexWrap::NoWrap => "flex-wrap:nowrap;",
            FlexWrap::Wrap => "flex-wrap:wrap;",
        }
        .into(),
    );
    if p.padding.top > 0.0
        || p.padding.right > 0.0
        || p.padding.bottom > 0.0
        || p.padding.left > 0.0
    {
        v.push(format!(
            "padding:{}px {}px {}px {}px;",
            p.padding.top as i32,
            p.padding.right as i32,
            p.padding.bottom as i32,
            p.padding.left as i32
        ));
    }
    v
}

/// E-9：GridParams → CSS 声明片段。
fn grid_css(g: &fd_canvas_core::GridParams) -> Vec<String> {
    use fd_canvas_core::TrackSizing;
    let mut v = vec!["display:grid;".to_string()];
    let cols: Vec<String> = g
        .columns
        .iter()
        .map(|t| match t {
            TrackSizing::Fixed(px) => format!("{}px", *px as i32),
            TrackSizing::Auto => "auto".into(),
            TrackSizing::Flex(f) => format!("{f}fr"),
            TrackSizing::Percent(pct) => format!("{pct}%"),
        })
        .collect();
    if !cols.is_empty() {
        v.push(format!("grid-template-columns:{};", cols.join(" ")));
    }
    let rows: Vec<String> = g
        .rows
        .iter()
        .map(|t| match t {
            TrackSizing::Fixed(px) => format!("{}px", *px as i32),
            TrackSizing::Auto => "auto".into(),
            TrackSizing::Flex(f) => format!("{f}fr"),
            TrackSizing::Percent(pct) => format!("{pct}%"),
        })
        .collect();
    if !rows.is_empty() {
        v.push(format!("grid-template-rows:{};", rows.join(" ")));
    }
    if g.gap.0 > 0.0 || g.gap.1 > 0.0 {
        v.push(format!("gap:{}px {}px;", g.gap.1 as i32, g.gap.0 as i32));
    }
    v
}

/// 按 design system 解析 token 引用（如 `color.bg` → 实际 hex）。
///
/// H-A11：递归遍历 children——旧实现只处理 page.nodes 顶层，嵌套节点的 token
/// 引用未被解析，codegen 输出残留 `token:xxx` 浏览器不认 / SwiftUI 未定义符号。
pub fn resolve_tokens(doc: &PenDocument, reg: &DesignSystemRegistry) -> PenDocument {
    let mut resolved = doc.clone();
    let resolve = |v: &Option<String>| -> Option<String> {
        let s = v.as_deref()?;
        if let Some(rest) = s.strip_prefix("token:") {
            return reg.lookup(rest).and_then(|tv| match tv {
                fd_design_system::TokenValue::Color(c) => Some(c.clone()),
                fd_design_system::TokenValue::String(s) => Some(s.clone()),
                _ => None,
            });
        }
        Some(s.to_string())
    };
    for page in &mut resolved.pages {
        for node in &mut page.nodes {
            resolve_tokens_recursive(node, &resolve);
        }
    }
    resolved
}

fn resolve_tokens_recursive(
    node: &mut PenNode,
    resolve: &impl Fn(&Option<String>) -> Option<String>,
) {
    node.style.fill = resolve(&node.style.fill);
    node.style.stroke = resolve(&node.style.stroke);
    // E-16：font_family 旧实现未经 resolve，token:font.mono 引用无法解析为实际字体栈。
    // robot-sim font.mono=String("SF Mono, Menlo, monospace")，经 resolve 闭包的 String arm 解析。
    node.style.font_family = resolve(&node.style.font_family);
    for child in &mut node.children {
        resolve_tokens_recursive(child, resolve);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_doc() -> PenDocument {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p1", "Home", 100.0, 100.0);
        let mut rect = PenNode::rect("n1", 10.0, 20.0, 50.0, 30.0);
        rect.style.fill = Some("#FFF".into());
        rect.style.stroke = Some("#000".into());
        page.add(rect);
        page.add(PenNode::text("n2", 5.0, 5.0, "hello"));
        doc.add_page(page);
        doc
    }

    #[test]
    fn html_codegen_basic() {
        let out = HtmlCodegen.generate(&sample_doc());
        assert!(out.contains("<!DOCTYPE html>"));
        assert!(out.contains("data-id=\"n1\""));
        assert!(out.contains("background:#FFF"));
        assert!(out.contains("hello"));
    }

    #[test]
    fn react_tailwind_basic() {
        let gen = ReactTailwindCodegen {
            component_name: "Home".into(),
        };
        let out = gen.generate(&sample_doc());
        assert!(out.contains("export function Home()"));
        assert!(out.contains("left-[10px]"));
        assert!(out.contains("bg-[#FFF]"));
    }

    // E-10 回归：node.id 含 `" onclick="alert(1)` 应转义，不得注入属性；
    // fill 含 `red;} * {background:url(http://evil)}` 应净化，不得逃逸 CSS 属性边界。
    #[test]
    fn codegen_escapes_xss_id_and_css() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut r = PenNode::rect("a\" onclick=\"alert(1)", 0.0, 0.0, 10.0, 10.0);
        r.style.fill = Some("red;} * { background: url(http://evil) }".into());
        page.add(r);
        doc.add_page(page);

        let html = HtmlCodegen.generate(&doc);
        assert!(
            !html.contains("onclick=\"alert(1)\""),
            "原始 onclick 不得残留"
        );
        assert!(
            html.contains("data-id=\"a&quot; onclick=&quot;alert(1)\""),
            "id 引号应转义为 &quot;"
        );
        assert!(!html.contains("url(http://evil)"), "fill url() 应被剥离");
        assert!(!html.contains("} * {"), "CSS 属性逃逸花括号应被剔除");
        // fill 含 url() → 降级 transparent，不得泄漏外网地址。
        assert!(
            html.contains("background:transparent"),
            "危险 fill 应降级 transparent"
        );

        let gen = ReactTailwindCodegen {
            component_name: "P".into(),
        };
        let react = gen.generate(&doc);
        assert!(
            !react.contains("url(http://evil)"),
            "Tailwind bg-[...] url() 应被剥离"
        );
    }

    #[test]
    fn tailwind_only_basic() {
        let out = TailwindOnlyCodegen.generate(&sample_doc());
        assert!(out.contains("absolute"));
        assert!(out.contains("left-[10px]"));
    }

    #[test]
    fn html_circle_gets_radius() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut c = PenNode::rect("c", 0.0, 0.0, 10.0, 10.0);
        c.kind = NodeKind::Circle;
        page.add(c);
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("border-radius:50%"));
    }

    #[test]
    fn react_group_recurses_children() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let g = PenNode::group(
            "g",
            0.0,
            0.0,
            vec![PenNode::rect("inner", 1.0, 1.0, 5.0, 5.0)],
        );
        page.add(g);
        doc.add_page(page);
        let gen = ReactTailwindCodegen {
            component_name: "C".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("data-id=\"inner\""));
    }

    #[test]
    fn html_group_recurses_children() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let g = PenNode::group(
            "g",
            0.0,
            0.0,
            vec![PenNode::rect("inner", 0.0, 0.0, 5.0, 5.0)],
        );
        page.add(g);
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("data-id=\"inner\""));
    }

    // F1/XSS 回归：node.text 含脚本载荷，HTML 输出必须转义，不可执行。
    #[test]
    fn html_text_escapes_script_payload() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let n = PenNode::text("t", 0.0, 0.0, "<img src=x onerror=alert(1)>");
        page.add(n);
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(
            !out.contains("<img src=x onerror"),
            "原始标签不得残留在 HTML 输出"
        );
        assert!(out.contains("&lt;img"), "必须转义为实体");
    }

    // F1/XSS 回归：React 输出同样转义。
    #[test]
    fn react_text_escapes_script_payload() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let n = PenNode::text("t", 0.0, 0.0, "<script>alert(1)</script>");
        page.add(n);
        doc.add_page(page);
        let gen = ReactTailwindCodegen {
            component_name: "XssTest".into(),
        };
        let out = gen.generate(&doc);
        assert!(
            !out.contains("<script>"),
            "原始 script 标签不得残留在 JSX 输出"
        );
        assert!(out.contains("&lt;script&gt;"), "必须转义为实体");
    }

    #[test]
    fn rect_with_children_renders_nested() {
        // parse-html 把带子节点的 <div> 映射为 Rect（非 Group）；
        // codegen 必须递归渲染其 children，否则往返丢失嵌套（#7）。
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut container = PenNode::rect("container", 0.0, 0.0, 80.0, 60.0);
        container.style.fill = Some("#FFF".into());
        container
            .children
            .push(PenNode::text("title", 5.0, 5.0, "标题"));
        container
            .children
            .push(PenNode::rect("btn", 5.0, 30.0, 40.0, 20.0));
        page.add(container);
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("data-id=\"container\""));
        assert!(out.contains("data-id=\"title\""));
        assert!(out.contains("data-id=\"btn\""));
        assert!(out.contains("标题"));
        // 子节点须出现在父节点开标签之后（嵌套而非丢弃）
        let c_pos = out.find("data-id=\"container\"").unwrap();
        let t_pos = out.find("data-id=\"title\"").unwrap();
        let b_pos = out.find("data-id=\"btn\"").unwrap();
        assert!(t_pos > c_pos, "title 应嵌套在 container 内");
        assert!(b_pos > c_pos, "btn 应嵌套在 container 内");
    }

    #[test]
    fn rect_with_children_renders_nested_react() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut container = PenNode::rect("container", 0.0, 0.0, 80.0, 60.0);
        container
            .children
            .push(PenNode::text("title", 5.0, 5.0, "标题"));
        container
            .children
            .push(PenNode::rect("btn", 5.0, 30.0, 40.0, 20.0));
        page.add(container);
        doc.add_page(page);
        let gen = ReactTailwindCodegen {
            component_name: "C".into(),
        };
        let out = gen.generate(&doc);
        let c_pos = out.find("data-id=\"container\"").unwrap();
        let t_pos = out.find("data-id=\"title\"").unwrap();
        let b_pos = out.find("data-id=\"btn\"").unwrap();
        assert!(t_pos > c_pos, "title 应嵌套在 container 内");
        assert!(b_pos > c_pos, "btn 应嵌套在 container 内");
    }

    #[test]
    fn codegen_target_labels() {
        assert_eq!(CodegenTarget::Html.label(), "html");
        assert_eq!(CodegenTarget::ReactTailwind.label(), "react-tailwind");
        assert_eq!(CodegenTarget::SwiftUi.label(), "swiftui");
    }

    #[test]
    fn resolve_tokens_replaces_token_refs() {
        use fd_design_system::DesignSystemRegistry;
        let mut reg = DesignSystemRegistry::new();
        reg.register_builtin();
        reg.activate("apple-hig").unwrap();
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n", 0.0, 0.0, 10.0, 10.0);
        n.style.fill = Some("token:color.accent".into());
        page.add(n);
        doc.add_page(page);
        let resolved = resolve_tokens(&doc, &reg);
        assert_eq!(
            resolved.pages[0].nodes[0].style.fill.as_deref(),
            Some("#007AFF")
        );
    }

    #[test]
    fn resolve_tokens_passthrough_non_token() {
        use fd_design_system::DesignSystemRegistry;
        let reg = DesignSystemRegistry::new();
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n", 0.0, 0.0, 10.0, 10.0);
        n.style.fill = Some("#ABC".into());
        page.add(n);
        doc.add_page(page);
        let resolved = resolve_tokens(&doc, &reg);
        assert_eq!(
            resolved.pages[0].nodes[0].style.fill.as_deref(),
            Some("#ABC")
        );
    }

    // H-A11：resolve_tokens 须递归 children——旧实现只处理顶层，嵌套 token 残留。
    #[test]
    fn resolve_tokens_recurses_children() {
        use fd_design_system::DesignSystemRegistry;
        let mut reg = DesignSystemRegistry::new();
        reg.register_builtin();
        reg.activate("apple-hig").unwrap();
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        // 顶层节点带嵌套子节点，子节点 fill 用 token 引用
        let mut child = PenNode::rect("child", 0.0, 0.0, 5.0, 5.0);
        child.style.fill = Some("token:color.accent".into());
        let mut parent = PenNode::group("parent", 0.0, 0.0, vec![child]);
        parent.style.fill = Some("token:color.accent".into());
        page.add(parent);
        doc.add_page(page);
        let resolved = resolve_tokens(&doc, &reg);
        let p = &resolved.pages[0].nodes[0];
        // 顶层解析
        assert_eq!(p.style.fill.as_deref(), Some("#007AFF"));
        // 嵌套 children 也解析（H-A11 修复前此处残留 token:color.accent）
        assert_eq!(
            p.children[0].style.fill.as_deref(),
            Some("#007AFF"),
            "嵌套子节点的 token 引用应被递归解析"
        );
    }

    // E-16 回归：resolve_tokens_recursive 旧实现仅处理 fill/stroke，font_family
    // 的 `token:font.mono` 引用无法解析为实际字体栈，codegen 输出残留 token 字面量。
    // 修复后 font_family 经 resolve 闭包的 String arm 解析。
    #[test]
    fn resolve_tokens_resolves_font_family_token_ref() {
        use fd_design_system::DesignSystemRegistry;
        let mut reg = DesignSystemRegistry::new();
        reg.register_builtin();
        reg.activate("robot-sim").unwrap();
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut n = PenNode::text("n", 0.0, 0.0, "hi");
        n.style.font_family = Some("token:font.mono".into());
        page.add(n);
        doc.add_page(page);
        let resolved = resolve_tokens(&doc, &reg);
        assert_eq!(
            resolved.pages[0].nodes[0].style.font_family.as_deref(),
            Some("SF Mono, Menlo, monospace"),
            "font_family token 引用应解析为实际字体栈（E-16）"
        );
    }

    #[test]
    fn swiftui_basic() {
        let gen = SwiftUiCodegen {
            view_name: "HomeView".into(),
        };
        let out = gen.generate(&sample_doc());
        assert!(out.contains("import SwiftUI"));
        assert!(out.contains("struct HomeView: View"));
        assert!(out.contains("Text(\"hello\")"));
    }

    #[test]
    fn swiftui_rect_with_frame() {
        let gen = SwiftUiCodegen {
            view_name: "TestView".into(),
        };
        let out = gen.generate(&sample_doc());
        assert!(out.contains(".frame(width: 50, height: 30)"));
    }

    #[test]
    fn swiftui_flex_becomes_hstack() {
        use fd_canvas_core::FlexParams;
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let inner = PenNode::rect("c", 0.0, 0.0, 10.0, 10.0);
        let mut group = PenNode::group("g", 0.0, 0.0, vec![inner]);
        group.style.layout = LayoutMode::Flex(FlexParams {
            direction: FlexDirection::Row,
            gap: 8.0,
            ..Default::default()
        });
        page.add(group);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "FlexView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("HStack(spacing: 8)"));
    }

    #[test]
    fn swiftui_flex_column_becomes_vstack() {
        use fd_canvas_core::FlexParams;
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let inner = PenNode::rect("c", 0.0, 0.0, 10.0, 10.0);
        let mut group = PenNode::group("g", 0.0, 0.0, vec![inner]);
        group.style.layout = LayoutMode::Flex(FlexParams {
            direction: FlexDirection::Column,
            gap: 12.0,
            ..Default::default()
        });
        page.add(group);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "ColView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("VStack(spacing: 12)"));
    }

    #[test]
    fn swiftui_free_layout_becomes_zstack() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let inner = PenNode::rect("c", 0.0, 0.0, 10.0, 10.0);
        let group = PenNode::group("g", 0.0, 0.0, vec![inner]);
        page.add(group);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "ZView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("ZStack"));
    }

    #[test]
    fn swiftui_token_extension() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n", 0.0, 0.0, 10.0, 10.0);
        n.style.fill = Some("#007AFF".into());
        n.style
            .design_token_refs
            .insert("fill".to_string(), "color.accent".to_string());
        page.add(n);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "TokenView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("extension Color"));
        assert!(out.contains("DesignTokens"));
        assert!(out.contains("color_accent"));
    }

    #[test]
    fn swiftui_circle() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut c = PenNode::rect("c", 0.0, 0.0, 20.0, 20.0);
        c.kind = NodeKind::Circle;
        page.add(c);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "CircleView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("Circle()"));
        assert!(out.contains("width: 20, height: 20"));
    }

    #[test]
    fn swiftui_image() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut img = PenNode::rect("img", 0.0, 0.0, 40.0, 40.0);
        img.kind = NodeKind::Image;
        page.add(img);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "ImgView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("Image(systemName: \"photo\")"));
    }

    #[test]
    fn swiftui_rect_with_children_wraps_zstack() {
        // 非 Group 叶子节点带子节点：SwiftUI 用 ZStack 承载，子节点不得丢失（#7）
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut container = PenNode::rect("container", 0.0, 0.0, 80.0, 60.0);
        container
            .children
            .push(PenNode::text("title", 5.0, 5.0, "标题"));
        page.add(container);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "NestView".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("ZStack {"), "非 Group 容器应外裹 ZStack");
        assert!(out.contains("Color.clear"), "叶子 Rect 应渲染");
        assert!(out.contains("Text(\"标题\")"), "子节点 Text 不得丢失");
    }

    // E-8 回归：codegen 必须输出 rotation/z_index/stroke_width/font_family/font_size 5 维。
    #[test]
    fn codegen_emits_all_style_dims_html() {
        let mut node = PenNode::rect("n1", 10.0, 20.0, 50.0, 30.0);
        node.rotation = 15.0;
        node.z_index = 10;
        node.style.stroke = Some("#000000".into());
        node.style.stroke_width = Some(5.0);
        node.style.font_size = Some(16.0);
        node.style.font_family = Some("system-ui".into());
        let mut page = Page::new("p1", "P", 100.0, 100.0);
        page.add(node);
        let mut doc = PenDocument::new();
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("transform:rotate(15deg)"), "应输出 rotation");
        assert!(out.contains("z-index:10"), "应输出 z_index");
        assert!(
            out.contains("border:5px solid"),
            "应输出 stroke_width=5 非 2"
        );
        assert!(out.contains("font-size:16px"), "应输出 font_size");
        assert!(out.contains("font-family:system-ui"), "应输出 font_family");
        // 旧实现固定 border:2px，回归确认不再固定 2px。
        assert!(!out.contains("border:2px solid"), "不得固定 2px 边框");
    }

    // E-8 回归：Tailwind 路径同样输出 5 维。
    #[test]
    fn codegen_emits_all_style_dims_tailwind() {
        let mut node = PenNode::rect("n1", 10.0, 20.0, 50.0, 30.0);
        node.rotation = 15.0;
        node.z_index = 10;
        node.style.stroke = Some("#000000".into());
        node.style.stroke_width = Some(5.0);
        node.style.font_size = Some(16.0);
        let mut page = Page::new("p1", "P", 100.0, 100.0);
        page.add(node);
        let mut doc = PenDocument::new();
        doc.add_page(page);
        let gen = ReactTailwindCodegen {
            component_name: "C".into(),
        };
        let out = gen.generate(&doc);
        assert!(out.contains("rotate-[15deg]"), "Tailwind 应输出 rotation");
        assert!(out.contains("z-[10]"), "Tailwind 应输出 z_index");
        assert!(
            out.contains("border-[5px]"),
            "Tailwind 应输出 stroke_width=5"
        );
        assert!(out.contains("text-[16px]"), "Tailwind 应输出 font_size");
        assert!(!out.contains("border-2"), "Tailwind 不得固定 border-2");
    }

    // E-9 回归：Flex 布局节点不得输出 absolute + left/top，应输出 display:flex + flex 属性。
    #[test]
    fn codegen_flex_not_absolute_html() {
        use fd_canvas_core::FlexParams;
        let mut node = PenNode::rect("flex1", 0.0, 0.0, 80.0, 60.0);
        node.style.layout = LayoutMode::Flex(FlexParams::default());
        let mut page = Page::new("p1", "P", 100.0, 100.0);
        page.add(node);
        let mut doc = PenDocument::new();
        doc.add_page(page);
        let out = HtmlCodegen.generate(&doc);
        assert!(out.contains("display:flex"), "Flex 应输出 display:flex");
        assert!(out.contains("flex-direction:row"), "应输出 flex-direction");
        assert!(
            !out.contains("position:absolute"),
            "Flex 容器不得 absolute 定位"
        );
    }

    // E-9 回归：Tailwind Flex 路径输出 flex 类，不输出 absolute。
    #[test]
    fn codegen_flex_not_absolute_tailwind() {
        use fd_canvas_core::FlexParams;
        let mut node = PenNode::rect("flex1", 0.0, 0.0, 80.0, 60.0);
        node.style.layout = LayoutMode::Flex(FlexParams::default());
        let mut page = Page::new("p1", "P", 100.0, 100.0);
        page.add(node);
        let mut doc = PenDocument::new();
        doc.add_page(page);
        let gen = ReactTailwindCodegen {
            component_name: "C".into(),
        };
        let out = gen.generate(&doc);
        assert!(
            out.contains("flex flex-row"),
            "Tailwind 应输出 flex flex-row"
        );
        assert!(
            !out.contains("absolute"),
            "Tailwind Flex 不得 absolute 定位"
        );
    }

    // E-8 回归（SwiftUI 路径）：rotation/z_index/stroke_width/font_family 4 维
    // 此前 SwiftUI 仅渲染 font_size，对齐 HTML/Tailwind/React 5 维完整渲染。
    #[test]
    fn swiftui_renders_rotation_zindex_stroke_width_font_family() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut r = PenNode::rect("n1", 10.0, 20.0, 50.0, 30.0);
        r.style.fill = Some("#FFF".into());
        r.style.stroke = Some("#000".into());
        r.style.stroke_width = Some(3.0);
        r.rotation = 45.0;
        r.z_index = 5;
        r.style.font_family = Some("Helvetica".into());
        r.style.font_size = Some(18.0);
        page.add(r);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "V".into(),
        };
        let out = gen.generate(&doc);
        assert!(
            out.contains(".rotationEffect(.degrees(45))"),
            "SwiftUI 应渲染 rotation: {}",
            out
        );
        assert!(
            out.contains(".zIndex(5)"),
            "SwiftUI 应渲染 z_index: {}",
            out
        );
        assert!(
            out.contains("lineWidth: 3"),
            "SwiftUI stroke 应使用 stroke_width 而非硬编码 1: {}",
            out
        );
        assert!(
            out.contains(".font(.custom(\"Helvetica\", size: 18))"),
            "SwiftUI 应渲染 font_family + font_size: {}",
            out
        );
    }

    // E-8 回归（SwiftUI 路径）：font_family 无 font_size 时回退 size:16。
    #[test]
    fn swiftui_font_family_without_size_falls_back() {
        let mut doc = PenDocument::new();
        let mut page = Page::new("p", "P", 100.0, 100.0);
        let mut r = PenNode::rect("n1", 0.0, 0.0, 50.0, 30.0);
        r.style.font_family = Some("Menlo".into());
        page.add(r);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "V".into(),
        };
        let out = gen.generate(&doc);
        assert!(
            out.contains(".font(.custom(\"Menlo\", size: 16))"),
            "font_family 无 size 应回退 16: {}",
            out
        );
    }

    #[test]
    fn escape_swift_string_escapes_injection_chars() {
        // R-6：反斜杠/引号/换行须转义
        assert_eq!(escape_swift_string("red"), "red");
        assert_eq!(
            escape_swift_string(r#"red"); evil(); /*"#),
            r#"red\"); evil(); /*"#
        );
        assert_eq!(escape_swift_string("a\nb"), r"a\nb");
        assert_eq!(escape_swift_string("back\\slash"), r"back\\slash");
    }

    #[test]
    fn swift_ui_color_escapes_named_color_injection() {
        // R-6：非 hex 命名色入 Color("...") 字面量。转义后每个 " 前必有 \。
        // 危险模式 = 裸 "（未被 \ 转义）闭合字面量。检查：恶意输入含 "，
        // 输出中所有 " 必须紧跟在 \ 之后（即 \" 形态），无裸 "。
        let evil = r#"red"); evil(); /*"#;
        let out = swift_ui_color(evil);
        assert!(
            out.contains("\\\""),
            "quote must be escaped to backslash-quote: {out}"
        );
        // 输出含 \" 表示已转义；进一步校验不存在未被转义的裸引号闭合注入：
        // 去掉所有 \" 后，剩余的 " 必为字面量定界符（恰好 2 个：Color(" 和 ")）。
        let stripped = out.replace("\\\"", "");
        let bare_quotes = stripped.matches('"').count();
        assert_eq!(
            bare_quotes, 2,
            "after removing escaped quotes, only 2 literal delimiters should remain: {out} -> {stripped}"
        );
    }

    #[test]
    fn swiftui_font_family_injection_blocked() {
        // R-6 端到端：font_family 注入面经 escape_swift_string 拦截。
        // 校验逻辑同上：去 \" 后仅余字面量定界引号。
        let mut doc = PenDocument::new();
        let mut page = Page::new("p1", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n1", 0.0, 0.0, 50.0, 30.0);
        n.style.font_family = Some(r#"Menlo"); evil(); /*"#.into());
        page.add(n);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "V".into(),
        };
        let out = gen.generate(&doc);
        assert!(
            out.contains(r#"Menlo\"); evil(); /*"#),
            "font_family quote must be escaped to backslash-quote: {out}"
        );
    }

    #[test]
    fn swiftui_fill_injection_blocked() {
        // R-6 端到端：非 hex fill 经 swift_ui_color 转义。
        let mut doc = PenDocument::new();
        let mut page = Page::new("p1", "P", 100.0, 100.0);
        let mut n = PenNode::rect("n1", 0.0, 0.0, 50.0, 30.0);
        n.style.fill = Some(r#"red"); evil(); /*"#.into());
        page.add(n);
        doc.add_page(page);
        let gen = SwiftUiCodegen {
            view_name: "V".into(),
        };
        let out = gen.generate(&doc);
        assert!(
            out.contains(r#"red\"); evil(); /*"#),
            "fill quote must be escaped to backslash-quote: {out}"
        );
    }
}
